/**
 * eslint.config.js
 * Single flat ESLint config for the whole monorepo:
 * - typescript-eslint recommended rules for every TS file,
 * - eslint-plugin-security for Node code (backend, scripts),
 * - react-hooks + jsx-a11y for the React frontend,
 * - eslint-config-prettier last so formatting is left to Prettier.
 * Spec: docs/spec/03 §3.2 (CI & quality) · docs/spec/09 (security)
 */
import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import reactHooks from 'eslint-plugin-react-hooks';
import security from 'eslint-plugin-security';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/coverage/**',
      // Prisma client generated by `prisma generate` (backend/src/generated/prisma).
      'backend/src/generated/**',
      'playwright-report/**',
      'test-results/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      // Allow intentionally unused args/vars when prefixed with "_" (e.g. Express `_req`).
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': 'error',
    },
  },
  // Node code: backend, shared, root scripts, tool configs.
  {
    files: [
      'backend/**/*.ts',
      'shared/**/*.ts',
      'scripts/**/*.{js,mjs}',
      'e2e/**/*.ts',
      '*.{js,ts}',
      'frontend/vite.config.ts',
    ],
    languageOptions: { globals: { ...globals.node } },
    ...security.configs.recommended,
  },
  // k6 load-test scripts (perf/) — run by the k6 binary, not Node; k6 injects its own globals.
  {
    files: ['perf/**/*.js'],
    languageOptions: { globals: { __ENV: 'readonly', __VU: 'readonly', __ITER: 'readonly' } },
  },
  // React frontend.
  {
    files: ['frontend/src/**/*.{ts,tsx}'],
    languageOptions: { globals: { ...globals.browser } },
    plugins: { 'react-hooks': reactHooks },
    rules: { ...reactHooks.configs.recommended.rules },
  },
  {
    files: ['frontend/src/**/*.tsx'],
    ...jsxA11y.flatConfigs.recommended,
  },
  prettier,
);
