export const en = {
  appName: "Campus Coin",
  common: {
    emailLabel: "Email address",
    passwordLabel: "Password",
    rememberMeLabel: "Remember me",
    submitLabel: "Submit",
    loadingLabel: "Loading...",
    backToLoginLabel: "Back to login",
    genericErrorTitle: "Something went wrong",
    genericErrorDetail: "Please try again in a moment.",
  },
  routes: {
    login: "/login",
    register: "/register",
    verifyEmail: "/verify-email",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    adminLogin: "/admin/login",
    home: "/",
    manageCategories: "/categories/manage",
    transactions: "/transactions",
    budgets: "/budgets",
    reports: "/reports",
    adminHome: "/admin",
  },
  layout: {
    themeToggleAriaLabel: "Toggle dark mode",
    switchToLight: "Light mode",
    switchToDark: "Dark mode",
    fontScaleLabel: "Text size",
    quickAddAriaLabel: "Quick add transaction",
    breadcrumbAriaLabel: "Breadcrumb",
    studentSideNavAriaLabel: "Student navigation",
    studentBottomNavAriaLabel: "Student mobile navigation",
    studentNav: {
      dashboard: "Dashboard",
      categories: "Categories",
      transactions: "Transactions",
      budgets: "Budgets",
      reports: "Reports",
      settings: "Settings",
    },
  },
  notFound: {
    title: "Page not found",
    detail: "The page you requested does not exist or has moved.",
    backAction: "Go to sign in",
  },
  errorPage: {
    reloadAction: "Reload page",
  },
  auth: {
    login: {
      title: "Welcome back",
      subtitle: "Sign in to manage your finances.",
      submitLabel: "Sign in",
      registerLinkLabel: "Create a student account",
      forgotPasswordLinkLabel: "Forgot your password?",
      successMessage: "Signed in successfully.",
      failureMessage: "Unable to sign in with the provided credentials.",
    },
    adminLogin: {
      title: "Admin sign in",
      subtitle: "Use your administrator account to continue.",
      submitLabel: "Sign in as admin",
      studentLoginLinkLabel: "Go to student sign in",
      successMessage: "Admin sign in successful.",
      failureMessage: "Unable to sign in as admin.",
    },
    register: {
      title: "Create your account",
      subtitle: "Start tracking your income and expenses.",
      fullNameLabel: "Full name",
      confirmPasswordLabel: "Confirm password",
      submitLabel: "Create account",
      loginLinkLabel: "Already have an account? Sign in",
      successMessage: "Registration successful. Please check your email for a verification link.",
      failureMessage: "Registration could not be completed.",
      passwordStrengthLabel: "Password strength",
      strengthLevels: ["Very weak", "Weak", "Fair", "Good", "Strong"],
    },
    verifyEmail: {
      title: "Verify your email",
      subtitle: "Paste your verification token or open this page from your email link.",
      tokenLabel: "Verification token",
      submitLabel: "Verify email",
      successMessage: "Your email has been verified. You can sign in now.",
      failureMessage: "Email verification failed.",
      missingTokenMessage: "No token found in the URL. Please paste your token.",
    },
    forgotPassword: {
      title: "Forgot password",
      subtitle: "Enter your email and we will send a password reset link if your account exists.",
      submitLabel: "Send reset link",
      successMessage: "If your account exists, a password reset link has been sent to your email.",
      failureMessage: "We could not process your request.",
    },
    resetPassword: {
      title: "Reset password",
      subtitle: "Set a new password for your account.",
      tokenLabel: "Reset token",
      confirmPasswordLabel: "Confirm password",
      submitLabel: "Reset password",
      successMessage: "Your password has been reset. Please sign in.",
      failureMessage: "Password reset failed.",
      missingTokenMessage: "No reset token found in the URL. Please paste your token.",
    },
    home: {
      studentTitle: "Student dashboard",
      studentSubtitle: "You are signed in. This protected area will host your dashboard modules.",
      adminTitle: "Admin dashboard",
      adminSubtitle: "You are signed in as admin. This protected area will host admin tools.",
      signOutLabel: "Sign out",
    },
  },
  categories: {
    title: "Manage My Categories",
    subtitle: "Create and maintain your personal income and expense categories.",
    typeTabsAriaLabel: "Category type",
    incomeTab: "Income",
    expenseTab: "Expense",
    addAction: "Add category",
    editAction: "Edit",
    deleteAction: "Delete",
    saveAction: "Save",
    cancelAction: "Cancel",
    confirmDeleteAction: "Delete category",
    createDialogTitle: "Create category",
    editDialogTitle: "Edit category",
    deleteDialogTitle: "Delete category",
    deleteDialogDescription:
      "If this category has existing transactions, choose a replacement category before deleting.",
    defaultBadge: "Default",
    personalBadge: "Personal",
    form: {
      nameLabel: "Category name",
      iconLabel: "Bootstrap icon",
      colorLabel: "Color",
      sortOrderLabel: "Sort order",
      reassignToLabel: "Reassign transactions to",
      reassignToPlaceholder: "Select replacement category",
    },
    messages: {
      created: "Category created successfully.",
      updated: "Category updated successfully.",
      deleted: "Category deleted successfully.",
      saveFailed: "Unable to save category.",
      deleteFailed: "Unable to delete category.",
    },
  },
  budgets: {
    title: "Monthly budgets",
    subtitle: "Set category limits and track spending progress by month.",
    monthLabel: "Month",
    copyPreviousAction: "Copy last month",
    saveAction: "Save budgets",
    deleteAction: "Delete",
    table: {
      categoryColumn: "Category",
      limitColumn: "Limit",
      thresholdColumn: "Alert threshold (%)",
      progressColumn: "Progress",
      actionsColumn: "Actions",
    },
    progress: {
      ok: "On track",
      near: "Near limit",
      exceeded: "Exceeded",
    },
    messages: {
      saved: "Budgets saved successfully.",
      saveFailed: "Unable to save budgets.",
      copied: "Copied {count} budget rows from last month.",
      copyFailed: "Unable to copy last month's budgets.",
      noRowsToSave: "Enter at least one budget limit before saving.",
      nothingToCopy: "No budgets were found in the previous month.",
    },
  },
  notifications: {
    bellAriaLabel: "Open notifications",
    dropdownTitle: "Notifications",
    markAllReadAction: "Mark all read",
    emptyState: "You're all caught up.",
    toastTitle: "Budget notification",
  },
  transactions: {
    title: "Transactions",
    subtitle: "Track your daily income and expenses.",
    monthLabel: "Month",
    typeLabel: "Type",
    addAction: "Add transaction",
    editAction: "Edit",
    deleteAction: "Delete",
    saveAction: "Save",
    cancelAction: "Cancel",
    createDialogTitle: "Create transaction",
    editDialogTitle: "Edit transaction",
    table: {
      dateColumn: "Date",
      categoryColumn: "Category",
      descriptionColumn: "Description",
      amountColumn: "Amount",
      sourceColumn: "Source",
      actionsColumn: "Actions",
    },
    form: {
      categoryLabel: "Category",
      amountLabel: "Amount",
      dateLabel: "Date",
      descriptionLabel: "Description",
      descriptionPlaceholder: "Optional note",
    },
    sourceLabels: {
      manual: "Manual",
      recurring: "Recurring",
      csvImport: "CSV import",
    },
    emptyState: "No transactions in this month yet.",
    messages: {
      created: "Transaction created successfully.",
      updated: "Transaction updated successfully.",
      deleted: "Transaction deleted successfully.",
      missingCategory: "Create at least one category for this type before adding a transaction.",
      switchedTypeToCreate: "Switched to {type} because the current tab has no categories.",
      saveFailed: "Unable to save transaction.",
      deleteFailed: "Unable to delete transaction.",
    },
  },
  dashboard: {
    title: "Dashboard",
    subtitle: "Overview of your money flow, budget, and monthly progress.",
    widgetErrorTitle: "Widget unavailable",
    widgetErrorDetail: "This widget could not be loaded. Please refresh and try again.",
    emptyTopCategory: "No spending yet",
    labels: {
      income: "Income",
      expense: "Expense",
      net: "Net",
      goal: "Goal",
    },
    widgets: {
      greeting: "Greeting",
      monthlyBalance: "This month balance",
      topCategory: "Top category",
      budgetVsActual: "Budget vs actual",
      expenseStructure: "Expense structure",
      sixMonthTrend: "6-month trend",
      netTrend: "Net trend",
      savingsGoal: "Savings goal",
      latestInsight: "Latest insight",
    },
    latestInsightPlaceholder: "Monthly AI insight will be available in a later phase.",
    a11y: {
      expenseStructureTableCaption: "Expense distribution table by category",
      sixMonthTrendTableCaption: "6-month income and expense trend table",
      netTrendTableCaption: "6-month net amount trend table",
    },
  },
  reports: {
    title: "Reports",
    subtitle: "Explore your spending patterns across category, month, and week.",
    exportPngAction: "Export PNG",
    exportPdfAction: "Export PDF",
    shareEmailAction: "Share via email",
    summaryTitle: "Summary",
    totalAmountLabel: "Total amount",
    totalTransactionsLabel: "Total transactions",
    sixMonthsSubtitle: "Last 6 months",
    dailyChartTitle: "Daily trend (current month)",
    weeklyChartTitle: "Weekly totals (current month)",
    forecastPlaceholder:
      "Forecast report is planned for Phase 13. This placeholder confirms the tab and routing behavior.",
    tabsAriaLabel: "Report types",
    tabs: {
      categoryBreakdown: "By category",
      incomeVsExpense: "Income vs expense (6 months)",
      dailyWeekly: "Daily and weekly (current month)",
      forecast: "Forecast",
    },
    filters: {
      rangeLabel: "Date range",
      typeLabel: "Transaction type",
      categoryLabel: "Category",
      monthLabel: "Month",
      allCategories: "All categories",
      sourceLabel: "Income source",
      allSources: "All sources",
      manualSource: "Manual",
      recurringSource: "Recurring",
      csvSource: "CSV import",
      thisMonth: "This month",
      lastMonth: "Last month",
      last3Months: "Last 3 months",
      last6Months: "Last 6 months",
    },
    series: {
      income: "Income",
      expense: "Expense",
      net: "Net",
    },
    messages: {
      exportPngFailed: "Could not export image. Please try again.",
      exportPdfFailed: "Could not export PDF. Please try again.",
      shareSuccess: "Report emailed successfully.",
      shareFailed: "Could not send the report. Please try again.",
    },
    shareModal: {
      title: "Share via email",
      description: "We'll send this month's report as a PDF attachment to the address below.",
      emailLabel: "Recipient email address",
      cancelAction: "Cancel",
      submitAction: "Send report",
    },
    a11y: {
      categoryTableCaption: "Category report table",
      incomeExpenseTableCaption: "Income versus expense by month",
      dailyWeeklyTableCaption: "Daily and weekly report table",
      weeklyTableCaption: "Weekly totals report table",
    },
  },
};

export type EnContent = typeof en;
