export const en = {
  appName: "Campus Coin",
  common: {
    emailLabel: "Email address",
    passwordLabel: "Password",
    rememberMeLabel: "Remember me",
    submitLabel: "Submit",
    loadingLabel: "Loading...",
    backToLoginLabel: "Back to login",
    genericErrorTitle: "Something went wrong",
    genericErrorDetail: "Please try again in a moment.",
  },
  routes: {
    login: "/login",
    register: "/register",
    verifyEmail: "/verify-email",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    adminLogin: "/admin/login",
    home: "/",
    manageCategories: "/categories/manage",
    adminHome: "/admin",
  },
  layout: {
    themeToggleAriaLabel: "Toggle dark mode",
    switchToLight: "Light mode",
    switchToDark: "Dark mode",
    fontScaleLabel: "Text size",
    quickAddAriaLabel: "Quick add transaction",
    studentSideNavAriaLabel: "Student navigation",
    studentBottomNavAriaLabel: "Student mobile navigation",
    studentNav: {
      dashboard: "Dashboard",
      categories: "Categories",
      transactions: "Transactions",
      budgets: "Budgets",
      reports: "Reports",
      settings: "Settings",
    },
  },
  notFound: {
    title: "Page not found",
    detail: "The page you requested does not exist or has moved.",
    backAction: "Go to sign in",
  },
  errorPage: {
    reloadAction: "Reload page",
  },
  auth: {
    login: {
      title: "Welcome back",
      subtitle: "Sign in to manage your finances.",
      submitLabel: "Sign in",
      registerLinkLabel: "Create a student account",
      forgotPasswordLinkLabel: "Forgot your password?",
      successMessage: "Signed in successfully.",
      failureMessage: "Unable to sign in with the provided credentials.",
    },
    adminLogin: {
      title: "Admin sign in",
      subtitle: "Use your administrator account to continue.",
      submitLabel: "Sign in as admin",
      studentLoginLinkLabel: "Go to student sign in",
      successMessage: "Admin sign in successful.",
      failureMessage: "Unable to sign in as admin.",
    },
    register: {
      title: "Create your account",
      subtitle: "Start tracking your income and expenses.",
      fullNameLabel: "Full name",
      confirmPasswordLabel: "Confirm password",
      submitLabel: "Create account",
      loginLinkLabel: "Already have an account? Sign in",
      successMessage: "Registration successful. Please check your email for a verification link.",
      failureMessage: "Registration could not be completed.",
      passwordStrengthLabel: "Password strength",
      strengthLevels: ["Very weak", "Weak", "Fair", "Good", "Strong"],
    },
    verifyEmail: {
      title: "Verify your email",
      subtitle: "Paste your verification token or open this page from your email link.",
      tokenLabel: "Verification token",
      submitLabel: "Verify email",
      successMessage: "Your email has been verified. You can sign in now.",
      failureMessage: "Email verification failed.",
      missingTokenMessage: "No token found in the URL. Please paste your token.",
    },
    forgotPassword: {
      title: "Forgot password",
      subtitle: "Enter your email and we will send a password reset link if your account exists.",
      submitLabel: "Send reset link",
      successMessage: "If your account exists, a password reset link has been sent to your email.",
      failureMessage: "We could not process your request.",
    },
    resetPassword: {
      title: "Reset password",
      subtitle: "Set a new password for your account.",
      tokenLabel: "Reset token",
      confirmPasswordLabel: "Confirm password",
      submitLabel: "Reset password",
      successMessage: "Your password has been reset. Please sign in.",
      failureMessage: "Password reset failed.",
      missingTokenMessage: "No reset token found in the URL. Please paste your token.",
    },
    home: {
      studentTitle: "Student dashboard",
      studentSubtitle: "You are signed in. This protected area will host your dashboard modules.",
      adminTitle: "Admin dashboard",
      adminSubtitle: "You are signed in as admin. This protected area will host admin tools.",
      signOutLabel: "Sign out",
    },
  },
  categories: {
    title: "Manage My Categories",
    subtitle: "Create and maintain your personal income and expense categories.",
    typeTabsAriaLabel: "Category type",
    incomeTab: "Income",
    expenseTab: "Expense",
    addAction: "Add category",
    editAction: "Edit",
    deleteAction: "Delete",
    saveAction: "Save",
    cancelAction: "Cancel",
    confirmDeleteAction: "Delete category",
    createDialogTitle: "Create category",
    editDialogTitle: "Edit category",
    deleteDialogTitle: "Delete category",
    deleteDialogDescription:
      "If this category has existing transactions, choose a replacement category before deleting.",
    defaultBadge: "Default",
    personalBadge: "Personal",
    form: {
      nameLabel: "Category name",
      iconLabel: "Bootstrap icon",
      colorLabel: "Color",
      sortOrderLabel: "Sort order",
      reassignToLabel: "Reassign transactions to",
      reassignToPlaceholder: "Select replacement category",
    },
    messages: {
      created: "Category created successfully.",
      updated: "Category updated successfully.",
      deleted: "Category deleted successfully.",
      saveFailed: "Unable to save category.",
      deleteFailed: "Unable to delete category.",
    },
  },
};

export type EnContent = typeof en;
