export const en = {
  appName: "Campus Coin",
  common: {
    emailLabel: "Email address",
    passwordLabel: "Password",
    rememberMeLabel: "Remember me",
    submitLabel: "Submit",
    loadingLabel: "Loading...",
    backToLoginLabel: "Back to login",
    genericErrorTitle: "Something went wrong",
    genericErrorDetail: "Please try again in a moment.",
  },
  routes: {
    login: "/login",
    register: "/register",
    verifyEmail: "/verify-email",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    adminLogin: "/admin/login",
    home: "/",
    adminHome: "/admin",
  },
  auth: {
    login: {
      title: "Welcome back",
      subtitle: "Sign in to manage your finances.",
      submitLabel: "Sign in",
      registerLinkLabel: "Create a student account",
      forgotPasswordLinkLabel: "Forgot your password?",
      successMessage: "Signed in successfully.",
      failureMessage: "Unable to sign in with the provided credentials.",
    },
    adminLogin: {
      title: "Admin sign in",
      subtitle: "Use your administrator account to continue.",
      submitLabel: "Sign in as admin",
      studentLoginLinkLabel: "Go to student sign in",
      successMessage: "Admin sign in successful.",
      failureMessage: "Unable to sign in as admin.",
    },
    register: {
      title: "Create your account",
      subtitle: "Start tracking your income and expenses.",
      fullNameLabel: "Full name",
      confirmPasswordLabel: "Confirm password",
      submitLabel: "Create account",
      loginLinkLabel: "Already have an account? Sign in",
      successMessage: "Registration successful. Please check your email for a verification link.",
      failureMessage: "Registration could not be completed.",
      passwordStrengthLabel: "Password strength",
      strengthLevels: ["Very weak", "Weak", "Fair", "Good", "Strong"],
    },
    verifyEmail: {
      title: "Verify your email",
      subtitle: "Paste your verification token or open this page from your email link.",
      tokenLabel: "Verification token",
      submitLabel: "Verify email",
      successMessage: "Your email has been verified. You can sign in now.",
      failureMessage: "Email verification failed.",
      missingTokenMessage: "No token found in the URL. Please paste your token.",
    },
    forgotPassword: {
      title: "Forgot password",
      subtitle: "Enter your email and we will send a password reset link if your account exists.",
      submitLabel: "Send reset link",
      successMessage: "If your account exists, a password reset link has been sent to your email.",
      failureMessage: "We could not process your request.",
    },
    resetPassword: {
      title: "Reset password",
      subtitle: "Set a new password for your account.",
      tokenLabel: "Reset token",
      confirmPasswordLabel: "Confirm password",
      submitLabel: "Reset password",
      successMessage: "Your password has been reset. Please sign in.",
      failureMessage: "Password reset failed.",
      missingTokenMessage: "No reset token found in the URL. Please paste your token.",
    },
    home: {
      studentTitle: "Student dashboard",
      studentSubtitle: "You are signed in. This protected area will host your dashboard modules.",
      adminTitle: "Admin dashboard",
      adminSubtitle: "You are signed in as admin. This protected area will host admin tools.",
      signOutLabel: "Sign out",
    },
  },
};

export type EnContent = typeof en;
