/**
 * generate-keys.mjs
 * Prints fresh secrets to paste into `.env` (nothing is written to disk):
 *  - JWT_PRIVATE_KEY / JWT_PUBLIC_KEY: Ed25519 key pair (PEM, newlines escaped as \n),
 *  - JWT_KID: random key id for key rotation,
 *  - DATA_ENCRYPTION_KEY: 32 random bytes (base64) for AES-256-GCM,
 *  - IP_HASH_SECRET: 32 random bytes (base64) used to HMAC client IPs.
 * Uses only Node's built-in `crypto` so it works on Windows without OpenSSL.
 * Usage: npm run keys:generate
 * Spec: docs/spec/10 §11.3, §11.4.2 · docs/spec/09 (key management)
 */
import { generateKeyPairSync, randomBytes } from 'node:crypto';

const SECRET_BYTES = 32; // 256-bit keys
const KID_BYTES = 8;

/**
 * Turn a multi-line PEM into one double-quoted .env value (dotenv/Node/Compose expand \n).
 * @param {string} pem - PEM text with real newlines.
 * @returns {string} quoted single-line value.
 */
function toEnvValue(pem) {
  return `"${pem.trim().replace(/\r?\n/g, '\\n')}"`;
}

const { privateKey, publicKey } = generateKeyPairSync('ed25519', {
  privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  publicKeyEncoding: { type: 'spki', format: 'pem' },
});

const lines = [
  '# ---- Generated by `npm run keys:generate` – paste into .env, never commit ----',
  `JWT_PRIVATE_KEY=${toEnvValue(privateKey)}`,
  `JWT_PUBLIC_KEY=${toEnvValue(publicKey)}`,
  `JWT_KID=${randomBytes(KID_BYTES).toString('hex')}`,
  `DATA_ENCRYPTION_KEY=${randomBytes(SECRET_BYTES).toString('base64')}`,
  'DATA_ENCRYPTION_KEY_VERSION=1',
  `IP_HASH_SECRET=${randomBytes(SECRET_BYTES).toString('base64')}`,
];

process.stdout.write(`${lines.join('\n')}\n`);
