-- =============================================================================
-- Migration: init (P02)
-- Generated by `prisma migrate dev --create-only`, then edited by hand:
--   1. Table collation utf8mb4_unicode_ci -> utf8mb4_0900_ai_ci (spec 06 §6.1).
--   2. CHECK constraints appended at the end (Prisma cannot model them).
-- Forward-only: never edit this file after it has been applied anywhere.
-- Spec: docs/spec/06 §6.1–§6.4
-- =============================================================================

-- CreateTable
CREATE TABLE `users` (
    `id` CHAR(36) NOT NULL,
    `email` VARCHAR(254) NOT NULL,
    `password_hash` VARCHAR(255) NOT NULL,
    `full_name` VARCHAR(100) NOT NULL,
    `role` ENUM('student', 'admin') NOT NULL DEFAULT 'student',
    `status` ENUM('pending', 'active', 'disabled') NOT NULL DEFAULT 'pending',
    `academic_year` VARCHAR(20) NULL,
    `monthly_allowance_baseline` DECIMAL(14, 2) NULL,
    `monthly_savings_goal` DECIMAL(14, 2) NULL,
    `currency` CHAR(3) NOT NULL DEFAULT 'USD',
    `timezone` VARCHAR(40) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
    `preferences` JSON NULL,
    `ai_opt_in` BOOLEAN NOT NULL DEFAULT false,
    `email_verified_at` DATETIME(3) NULL,
    `failed_login_count` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `locked_until` DATETIME(3) NULL,
    `mfa_secret_enc` VARBINARY(255) NULL,
    `mfa_recovery_codes` JSON NULL,
    `last_login_at` DATETIME(3) NULL,
    `deleted_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `users_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `refresh_tokens` (
    `id` CHAR(36) NOT NULL,
    `user_id` CHAR(36) NOT NULL,
    `token_hash` CHAR(64) NOT NULL,
    `family_id` CHAR(36) NOT NULL,
    `user_agent` VARCHAR(255) NULL,
    `ip_hash` CHAR(64) NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `revoked_at` DATETIME(3) NULL,
    `replaced_by_id` CHAR(36) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `refresh_tokens_token_hash_key`(`token_hash`),
    INDEX `refresh_tokens_user_id_idx`(`user_id`),
    INDEX `refresh_tokens_family_id_idx`(`family_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `auth_tokens` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` CHAR(36) NOT NULL,
    `purpose` ENUM('verify_email', 'reset_password') NOT NULL,
    `token_hash` CHAR(64) NOT NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `used_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `auth_tokens_token_hash_key`(`token_hash`),
    INDEX `auth_tokens_user_id_idx`(`user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `categories` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` CHAR(36) NULL,
    `owner_key` VARCHAR(36) NOT NULL,
    `name` VARCHAR(50) NOT NULL,
    `type` ENUM('income', 'expense') NOT NULL,
    `icon` VARCHAR(40) NULL,
    `color` CHAR(7) NULL,
    `is_default` BOOLEAN NOT NULL DEFAULT false,
    `is_active` BOOLEAN NOT NULL DEFAULT true,
    `sort_order` SMALLINT NOT NULL DEFAULT 0,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `categories_user_id_idx`(`user_id`),
    UNIQUE INDEX `categories_owner_key_type_name_key`(`owner_key`, `type`, `name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `transactions` (
    `id` CHAR(36) NOT NULL,
    `user_id` CHAR(36) NOT NULL,
    `category_id` INTEGER NOT NULL,
    `type` ENUM('income', 'expense') NOT NULL,
    `amount` DECIMAL(14, 2) NOT NULL,
    `currency` CHAR(3) NOT NULL,
    `description` VARCHAR(255) NULL,
    `merchant_key` VARCHAR(100) NULL,
    `txn_date` DATE NOT NULL,
    `source` ENUM('manual', 'recurring', 'csv_import') NOT NULL DEFAULT 'manual',
    `recurring_rule_id` INTEGER NULL,
    `recurring_period` CHAR(10) NULL,
    `import_batch_id` CHAR(36) NULL,
    `ai_suggested_category_id` INTEGER NULL,
    `ai_confidence` DECIMAL(4, 3) NULL,
    `category_source` ENUM('user', 'ai_accepted', 'ai_overridden', 'rule', 'import') NOT NULL DEFAULT 'user',
    `is_anomaly` BOOLEAN NOT NULL DEFAULT false,
    `is_possible_duplicate` BOOLEAN NOT NULL DEFAULT false,
    `version` INTEGER NOT NULL DEFAULT 1,
    `deleted_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `transactions_user_id_deleted_at_txn_date_idx`(`user_id`, `deleted_at`, `txn_date` DESC),
    INDEX `transactions_user_id_category_id_txn_date_idx`(`user_id`, `category_id`, `txn_date`),
    INDEX `transactions_user_id_type_txn_date_idx`(`user_id`, `type`, `txn_date`),
    INDEX `transactions_user_id_merchant_key_idx`(`user_id`, `merchant_key`),
    INDEX `transactions_merchant_key_idx`(`merchant_key`),
    UNIQUE INDEX `transactions_recurring_rule_id_recurring_period_key`(`recurring_rule_id`, `recurring_period`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `transaction_history` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `transaction_id` CHAR(36) NOT NULL,
    `user_id` CHAR(36) NOT NULL,
    `action` ENUM('create', 'update', 'delete', 'restore') NOT NULL,
    `snapshot` JSON NOT NULL,
    `changed_fields` JSON NULL,
    `changed_by` CHAR(36) NOT NULL,
    `changed_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `transaction_history_transaction_id_changed_at_idx`(`transaction_id`, `changed_at`),
    INDEX `transaction_history_user_id_idx`(`user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `recurring_rules` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` CHAR(36) NOT NULL,
    `category_id` INTEGER NOT NULL,
    `type` ENUM('income', 'expense') NOT NULL,
    `amount` DECIMAL(14, 2) NOT NULL,
    `description` VARCHAR(255) NULL,
    `frequency` ENUM('weekly', 'monthly', 'yearly') NOT NULL,
    `interval_count` TINYINT NOT NULL DEFAULT 1,
    `day_of_month` TINYINT NULL,
    `day_of_week` TINYINT NULL,
    `start_date` DATE NOT NULL,
    `end_date` DATE NULL,
    `next_run_date` DATE NOT NULL,
    `is_active` BOOLEAN NOT NULL DEFAULT true,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `recurring_rules_is_active_next_run_date_idx`(`is_active`, `next_run_date`),
    INDEX `recurring_rules_user_id_idx`(`user_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `budgets` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` CHAR(36) NOT NULL,
    `category_id` INTEGER NOT NULL,
    `month` DATE NOT NULL,
    `limit_amount` DECIMAL(14, 2) NOT NULL,
    `alert_threshold_pct` TINYINT NOT NULL DEFAULT 80,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `budgets_category_id_idx`(`category_id`),
    UNIQUE INDEX `budgets_user_id_category_id_month_key`(`user_id`, `category_id`, `month`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `insights` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` CHAR(36) NOT NULL,
    `month` DATE NOT NULL,
    `summary_text` TEXT NULL,
    `tip_text` TEXT NULL,
    `flagged_patterns` JSON NULL,
    `stats_snapshot` JSON NULL,
    `generator` ENUM('llm', 'template') NOT NULL,
    `model` VARCHAR(60) NULL,
    `prompt_version` VARCHAR(20) NULL,
    `status` ENUM('queued', 'processing', 'completed', 'failed') NOT NULL,
    `regenerate_count` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `generated_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `insights_user_id_month_key`(`user_id`, `month`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `tip_templates` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(40) NOT NULL,
    `rule_type` ENUM('over_budget', 'above_average', 'small_frequent', 'subscriptions', 'savings_gap', 'weekend_spike', 'general') NOT NULL,
    `title_tpl` VARCHAR(150) NOT NULL,
    `body_tpl` VARCHAR(500) NOT NULL,
    `locale` VARCHAR(5) NOT NULL DEFAULT 'en',
    `is_active` BOOLEAN NOT NULL DEFAULT true,
    `created_by` CHAR(36) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `tip_templates_code_key`(`code`),
    INDEX `tip_templates_rule_type_is_active_idx`(`rule_type`, `is_active`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `user_tips` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` CHAR(36) NOT NULL,
    `template_id` INTEGER NOT NULL,
    `category_id` INTEGER NULL,
    `period` DATE NOT NULL,
    `rendered_title` VARCHAR(200) NOT NULL,
    `rendered_body` VARCHAR(600) NOT NULL,
    `impact_amount` DECIMAL(14, 2) NOT NULL,
    `score` DECIMAL(12, 4) NOT NULL,
    `status` ENUM('active', 'pinned', 'dismissed') NOT NULL DEFAULT 'active',
    `dismissed_until` DATE NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `user_tips_score_idx`(`score`),
    INDEX `user_tips_template_id_idx`(`template_id`),
    UNIQUE INDEX `user_tips_user_id_template_id_category_id_period_key`(`user_id`, `template_id`, `category_id`, `period`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `ai_category_rules` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` CHAR(36) NOT NULL,
    `merchant_key` VARCHAR(100) NOT NULL,
    `category_id` INTEGER NOT NULL,
    `hit_count` INTEGER UNSIGNED NOT NULL DEFAULT 1,
    `last_used_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `ai_category_rules_category_id_idx`(`category_id`),
    UNIQUE INDEX `ai_category_rules_user_id_merchant_key_key`(`user_id`, `merchant_key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `notifications` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` CHAR(36) NOT NULL,
    `type` ENUM('budget_near', 'budget_exceeded', 'insight_ready', 'anomaly', 'duplicate', 'system') NOT NULL,
    `title` VARCHAR(150) NOT NULL,
    `body` VARCHAR(500) NULL,
    `payload` JSON NULL,
    `dedupe_key` VARCHAR(100) NOT NULL,
    `read_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `notifications_user_id_read_at_created_at_idx`(`user_id`, `read_at`, `created_at`),
    UNIQUE INDEX `notifications_user_id_dedupe_key_key`(`user_id`, `dedupe_key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `bookmarks` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` CHAR(36) NOT NULL,
    `target_type` ENUM('tip', 'insight', 'report') NOT NULL,
    `target_ref` VARCHAR(64) NOT NULL,
    `note` VARCHAR(500) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `bookmarks_user_id_target_type_target_ref_key`(`user_id`, `target_type`, `target_ref`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `import_batches` (
    `id` CHAR(36) NOT NULL,
    `user_id` CHAR(36) NOT NULL,
    `original_filename` VARCHAR(255) NOT NULL,
    `file_sha256` CHAR(64) NOT NULL,
    `status` ENUM('uploaded', 'parsing', 'previewed', 'committed', 'failed', 'expired') NOT NULL DEFAULT 'uploaded',
    `total_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `valid_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `committed_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `error_report` JSON NULL,
    `committed_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `import_batches_user_id_file_sha256_key`(`user_id`, `file_sha256`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `recent_activity` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` CHAR(36) NOT NULL,
    `transaction_id` CHAR(36) NOT NULL,
    `action` ENUM('viewed', 'edited') NOT NULL,
    `occurred_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `recent_activity_user_id_occurred_at_idx`(`user_id`, `occurred_at`),
    INDEX `recent_activity_transaction_id_idx`(`transaction_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `announcements` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(150) NOT NULL,
    `body` VARCHAR(1000) NOT NULL,
    `level` ENUM('info', 'warning') NOT NULL DEFAULT 'info',
    `starts_at` DATETIME(3) NOT NULL,
    `ends_at` DATETIME(3) NULL,
    `is_active` BOOLEAN NOT NULL DEFAULT true,
    `created_by` CHAR(36) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `announcements_is_active_starts_at_ends_at_idx`(`is_active`, `starts_at`, `ends_at`),
    INDEX `announcements_created_by_idx`(`created_by`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- CreateTable
CREATE TABLE `audit_logs` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `actor_id` CHAR(36) NULL,
    `actor_role` VARCHAR(20) NULL,
    `action` VARCHAR(80) NOT NULL,
    `entity_type` VARCHAR(40) NULL,
    `entity_id` VARCHAR(64) NULL,
    `ip_hash` CHAR(64) NULL,
    `user_agent` VARCHAR(255) NULL,
    `metadata` JSON NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `audit_logs_actor_id_created_at_idx`(`actor_id`, `created_at`),
    INDEX `audit_logs_action_created_at_idx`(`action`, `created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- AddForeignKey
ALTER TABLE `refresh_tokens` ADD CONSTRAINT `refresh_tokens_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `auth_tokens` ADD CONSTRAINT `auth_tokens_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `categories` ADD CONSTRAINT `categories_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `transactions` ADD CONSTRAINT `transactions_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `transactions` ADD CONSTRAINT `transactions_category_id_fkey` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `transactions` ADD CONSTRAINT `transactions_recurring_rule_id_fkey` FOREIGN KEY (`recurring_rule_id`) REFERENCES `recurring_rules`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `transactions` ADD CONSTRAINT `transactions_import_batch_id_fkey` FOREIGN KEY (`import_batch_id`) REFERENCES `import_batches`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `recurring_rules` ADD CONSTRAINT `recurring_rules_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `recurring_rules` ADD CONSTRAINT `recurring_rules_category_id_fkey` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `budgets` ADD CONSTRAINT `budgets_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `budgets` ADD CONSTRAINT `budgets_category_id_fkey` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `insights` ADD CONSTRAINT `insights_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tip_templates` ADD CONSTRAINT `tip_templates_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `user_tips` ADD CONSTRAINT `user_tips_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `user_tips` ADD CONSTRAINT `user_tips_template_id_fkey` FOREIGN KEY (`template_id`) REFERENCES `tip_templates`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ai_category_rules` ADD CONSTRAINT `ai_category_rules_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ai_category_rules` ADD CONSTRAINT `ai_category_rules_category_id_fkey` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `notifications` ADD CONSTRAINT `notifications_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `bookmarks` ADD CONSTRAINT `bookmarks_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `import_batches` ADD CONSTRAINT `import_batches_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `recent_activity` ADD CONSTRAINT `recent_activity_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `recent_activity` ADD CONSTRAINT `recent_activity_transaction_id_fkey` FOREIGN KEY (`transaction_id`) REFERENCES `transactions`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `announcements` ADD CONSTRAINT `announcements_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- =============================================================================
-- Hand-written CHECK constraints (MySQL 8.0.16+ enforces them).
-- Prisma does not model CHECKs, so they cause no drift in later migrations.
-- =============================================================================

-- BR-TX-01: amounts are always positive; the type gives the sign.
ALTER TABLE `transactions` ADD CONSTRAINT `chk_transactions_amount_positive` CHECK (`amount` > 0);
ALTER TABLE `transactions` ADD CONSTRAINT `chk_transactions_ai_confidence_range` CHECK (`ai_confidence` IS NULL OR (`ai_confidence` >= 0 AND `ai_confidence` <= 1));
ALTER TABLE `recurring_rules` ADD CONSTRAINT `chk_recurring_rules_amount_positive` CHECK (`amount` > 0);
ALTER TABLE `recurring_rules` ADD CONSTRAINT `chk_recurring_rules_interval_count` CHECK (`interval_count` BETWEEN 1 AND 12);
ALTER TABLE `budgets` ADD CONSTRAINT `chk_budgets_limit_positive` CHECK (`limit_amount` > 0);
ALTER TABLE `budgets` ADD CONSTRAINT `chk_budgets_alert_threshold` CHECK (`alert_threshold_pct` BETWEEN 50 AND 100);
ALTER TABLE `users` ADD CONSTRAINT `chk_users_allowance_non_negative` CHECK (`monthly_allowance_baseline` IS NULL OR `monthly_allowance_baseline` >= 0);
ALTER TABLE `users` ADD CONSTRAINT `chk_users_savings_goal_non_negative` CHECK (`monthly_savings_goal` IS NULL OR `monthly_savings_goal` >= 0);
ALTER TABLE `insights` ADD CONSTRAINT `chk_insights_regenerate_count` CHECK (`regenerate_count` <= 3);

-- owner_key replaces the spec's generated column COALESCE(user_id,'SYSTEM'); the service sets it,
-- this CHECK guarantees it. Allowed because categories.user_id's FK uses RESTRICT (MySQL forbids
-- CHECKs on columns of FKs with CASCADE/SET NULL actions).
ALTER TABLE `categories` ADD CONSTRAINT `chk_categories_owner_key` CHECK (`owner_key` = COALESCE(`user_id`, 'SYSTEM'));
